---
title: 'Testserver'
footer: 'External configuration from srv-config.yml'
use_mysql: false
mysql_endpoint: 'localhost:3306'
mysql_user: 'mysql_user'
mysql_password: 'mysql_pass'
use_rabbitmq: false
rbmq_endpoint: 'localhost:5672'
rbmq_user: 'rbmq_user'
rbmq_password: 'rbmq_pass'
config_file: './srv-config.yml'

access_log: os.environ.get('ACCESS_LOG') or None
error_log: os.environ.get('ERROR_LOG') or None
LOG_LINES: 30

redis_url: os.environ.get("REDIS_URL") or None
redis_server: os.environ.get('REDIS_SERVER') or None
redis_port: os.environ.get('REDIS_PORT') or 6379
redis_html_counter: 'api_srv_html_counter'
redis_api_counter: 'api_srv_counter'