version: 2.1

jobs:
  unit-testing:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          name: "Install python environment"
          command: "make install"
      - run:
          name: "Run linter"
          command: "make lint"
      - run:
          name: "Run tests"
          command: "make test"

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   test-server-testing:
#     jobs:
#       - unit-testing