---
name: Unit tests
on:
  pull_request:
    branches: [ "master" ]

jobs:  
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
     # Runs a single command using the runners shell
      - name: Check and prepare environment
        run: |
          ls -lh
          make --version
          docker --version 
          python --version
          python3 --version
          pip --version
          pip install -r requirements-dev.txt
      - name: lint
        run: make lint
        
      - name: test
        run: make test
