# This is a basic workflow that is manually triggered

name: Linting and unit testing

# Run on every push.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Install and prepare environment
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
     # Runs a single command using the runners shell
      - name: Check environment
        run: |
          ls -lh
          make --version
          docker --version 
          python --version
          python3 --version
          pip --version

      - name: lint
        run: make lint
        
      - name: test
        run: make test
